#%RAML 1.0 DataType
description: use this type for inventory batch
type: object
properties:
  product:
    type: string
    required: true
    maxLength: 100
    description: The localized name of the product.
  store:
    type: string
    required: true
    maxLength: 100
    description: The localized name of the store.
  amount:
    type: number
    required: true
    description: The actual amount