#%RAML 1.0 DataType
type: object
properties: 
  active:
    type: string
    required: false
    description: Incident Creation Field
  activityDue:
    type: string
    required: false
    description: Incident Creation Field
  additionalAssigneeList:
    type: string
    required: false
    description: Incident Creation Field
  approval:
    type: string
    required: false
    description: Incident Creation Field
  approvalHistory:
    type: string
    required: false
    description: Incident Creation Field
  approvalSet:
    type: string
    required: false
    description: Incident Creation Field
  assignedTo:
    type: string
    required: false
    description: Incident Creation Field
  assignedGroup:
    type: string
    required: false
    description: Incident Creation Field
  businessDuration:
    type: string
    required: false
    description: Incident Creation Field
  businessService:
    type: string
    required: false
    description: Incident Creation Field
  businessStc:
    type: string
    required: false
    description: Incident Creation Field
  calendarDuration:
    type: string
    required: false
    description: Incident Creation Field
  calendarStc:
    type: string
    required: false
    description: Incident Creation Field
  callerId:
    type: string
    required: false
    description: Incident Creation Field
  category:
    type: string
    required: false
    description: Incident Creation Field
  causedBy:
    type: string
    required: false
    description: Incident Creation Field
  childIncidents:
    type: string
    required: false
    description: Incident Creation Field
  closeNote:
    type: string
    required: false
    description: Incident Creation Field
  closeCode:
    type: string
    required: false
    description: Incident Creation Field
  closedAt:
    type: string
    required: false
    description: Incident Creation Field
  closedBy:
    type: string
    required: false
    description: Incident Creation Field
  cmdbCi:
    type: string
    required: false
    description: Incident Creation Field
  comments:
    type: string
    required: true
    description: Incident Creation Field
  commentsAndWorkNotes:
    type: string
    required: false
    description: Incident Creation Field
  company:
    type: string
    required: false
    description: Incident Creation Field
  contactType:
    type: string
    required: false
    description: Incident Creation Field
  correlationDisplay:
    type: string
    required: false
    description: Incident Creation Field
  correlationId:
    type: string
    required: false
    description: Incident Creation Field
  deliveryPlan:
    type: string
    required: false
    description: Incident Creation Field
  deliveryTask:
    type: string
    required: false
    description: Incident Creation Field
  description:
    type: string
    required: false
    description: Incident Creation Field
  dueDate:
    type: string
    required: false
    description: Incident Creation Field
  escalation:
    type: string
    required: false
    description: Incident Creation Field
  expectedStart:
    type: string
    required: false
    description: Incident Creation Field
  followUp:
    type: string
    required: false
    description: Incident Creation Field
  groupList:
    type: string
    required: false
    description: Incident Creation Field
  holdReason:
    type: string
    required: false
    description: Incident Creation Field
  impact:
    type: string
    required: false
    description: Incident Creation Field
  incident_state:
    type: string
    required: false
    description: Incident Creation Field
  knowlegde:
    type: string
    required: false
    description: Incident Creation Field
  location:
    type: string
    required: false
    description: Incident Creation Field
  madeSla:
    type: string
    required: false
    description: Incident Creation Field
  notify:
    type: string
    required: false
    description: Incident Creation Field
  string:
    type: string
    required: false
    description: Incident Creation Field
  openedAt:
    type: string
    required: false
    description: Incident Creation Field
  openedBy:
    type: string
    required: false
    description: Incident Creation Field
  order:
    type: string
    required: false
    description: Incident Creation Field
  parent:
    type: string
    required: false
    description: Incident Creation Field
  parentIncident:
    type: string
    required: false
    description: Incident Creation Field
  priority:
    type: string
    required: false
    description: Incident Creation Field
  problemId:
    type: string
    required: false
    description: Incident Creation Field
  reassignmentCount:
    type: string
    required: false
    description: Incident Creation Field
  reopenCount:
    type: string
    required: false
    description: Incident Creation Field
  reopenedBy:
    type: string
    required: false
    description: Incident Creation Field
  reopenedTime:
    type: string
    required: false
    description: Incident Creation Field
  resolvedAt:
    type: string
    required: false
    description: Incident Creation Field
  resolvedBy:
    type: string
    required: false
    description: Incident Creation Field
  rfc:
    type: string
    required: false
    description: Incident Creation Field
  severity:
    type: string
    required: false
    description: Incident Creation Field
  shortDescription:
    type: string
    required: true
    description: Incident Creation Field
  slaDue:
    type: string
    required: false
    description: Incident Creation Field
  state:
    type: string
    required: false
    description: Incident Creation Field
  subCategory:
    type: string
    required: false
    description: Incident Creation Field
  timeWorked:
    type: string
    required: false
    description: Incident Creation Field
  uponApproval:
    type: string
    required: false
    description: Incident Creation Field
  uponReject:
    type: string
    required: false
    description: Incident Creation Field
  urgency:
    type: string
    required: false
    description: Incident Creation Field
  userInput:
    type: string
    required: false
    description: Incident Creation Field
  watchList:
    type: string
    required: false
    description: Incident Creation Field
  workEnd:
    type: string
    required: false
    description: Incident Creation Field
  workNotes:
    type: string
    required: false
    description: Incident Creation Field
  workNotesList:
    type: string
    required: false
    description: Incident Creation Field
  workStart:
    type: string
    required: false
    description: Incident Creation Field
  sfdcCaseId:
    type: string
    required: false
    description: Salesforce Case Id used to maintain correlation between SFDC and SNOW
  

  