#%RAML 1.0 DataType
description: use this type for product variant
type: object
properties:
  productId:
    type: string
    required: false
    maxLength: 50
    description: The ID (SKU) of the product.
  variationAttributes:
    type: object
    properties:
      size:
        type: string
        required: false
      color:
        type: string
        required: false
    additionalProperties: true
      